/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/category`; params?: Router.UnknownInputParams; } | { pathname: `/counselor-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/counselor-signin`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/post`; params?: Router.UnknownInputParams; } | { pathname: `/user-home`; params?: Router.UnknownInputParams; } | { pathname: `/user-signin`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useFormattedDate`; params?: Router.UnknownInputParams; } | { pathname: `/counselor-signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/chat/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/category`; params?: Router.UnknownOutputParams; } | { pathname: `/counselor-dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/counselor-signin`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/post`; params?: Router.UnknownOutputParams; } | { pathname: `/user-home`; params?: Router.UnknownOutputParams; } | { pathname: `/user-signin`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useFormattedDate`; params?: Router.UnknownOutputParams; } | { pathname: `/counselor-signup`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `/chat/[postId]`, params: Router.UnknownOutputParams & { postId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/category${`?${string}` | `#${string}` | ''}` | `/counselor-dashboard${`?${string}` | `#${string}` | ''}` | `/counselor-signin${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/post${`?${string}` | `#${string}` | ''}` | `/user-home${`?${string}` | `#${string}` | ''}` | `/user-signin${`?${string}` | `#${string}` | ''}` | `/../hooks/useFormattedDate${`?${string}` | `#${string}` | ''}` | `/counselor-signup${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/category`; params?: Router.UnknownInputParams; } | { pathname: `/counselor-dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/counselor-signin`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/post`; params?: Router.UnknownInputParams; } | { pathname: `/user-home`; params?: Router.UnknownInputParams; } | { pathname: `/user-signin`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useFormattedDate`; params?: Router.UnknownInputParams; } | { pathname: `/counselor-signup`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/+not-found` | `/chat/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `/chat/[postId]`, params: Router.UnknownInputParams & { postId: string | number; } };
    }
  }
}
